[files]
extend-exclude = [
    ".git/",
    "3rd-party",
    "talks/phpstan-dba@phpugffm/assets/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bmaks-rafalko\\b",
]

[default.extend-identifiers]
# Typos
"Github" = "GitHub"

# Don't correct this words
[default.extend-words]
Symplify = "Symplify"
ser = "ser" # $coverage = unserialize(file_get_contents(__DIR__ . '/coverage-data.ser'));
